### ISSUE TITLE
Replace the text "Previous article" and "Next article"

### ISSUE THREAD

**Issue by LDI-DAN** [heimrichhannot/contao-newsnavigation-bundle#1]
Good afternoon, I need to replace the text "Previous article" and "Next article" with the headlines (title) of the news in the "news" module. Tell me please how can I do this?
Thank you in advance

**Comment by fatcrobat** [comment]
Use `{{news_title::<?= $this->nextArticle; ?>}}` or `{{news_title::<?= $this->previousArticle; ?>}}` Inserttags and replace `$this->nextArticleLabel` or `$this->previousArticleLabel` in you news template to achieve that.

**Comment by LDI-DAN** [comment]
"Fatcrobat" thank you for your help.
