### ISSUE TITLE
Navigation only in the same archive

### ISSUE THREAD

**Issue by thepixture** [heimrichhannot/contao-newsnavigation-bundle#2]
Is it possible to navigate only in the news archive i've selected in the reader module?

**Comment by koertho** [comment]
That is not possible in the current implementation. This function requires a custom news module. 
You can implement this and do a pull request or check our [news bundle](https://github.com/heimrichhannot/contao-news-bundle), which contains a more funtional news navigation.

**Comment by koertho** [comment]
I have given this some thoughts and see the point. This should be the default way (navigate within the same news archive). It should be possible by customizing the news model, maybe I'll find some time today or the next days.

**Comment by thepixture** [comment]
Ok thanks ... i appreciate that.

**Comment by thepixture** [comment]
Any progess?

**Comment by koertho** [comment]
@thepixture Progress yes, but not yet finished. Busy time. Hope I get it this week. Sorry for the delay

**Comment by koertho** [comment]
Fixed in version 2.0.0

**Comment by thepixture** [comment]
Great job.

There are only a few spelling mistakes left, inside the reader module.

**Comment by koertho** [comment]
Can you please open a new issue for this? Or a pull request, if you like :)
