### ISSUE TITLE
Enhancement: Sort articles by backend list

### ISSUE THREAD

**Issue by k-webdesign** [heimrichhannot/contao-newsnavigation-bundle#5]
Hi,

is it possible to sort the articles by the backend filters? Sometimes they're sort by author or anything else and I need a pagination that matches this sorting. 

Bye bye,
Kim

**Comment by koertho** [comment]
No, it is not possible to sort by backend filters. They have no impact on the frontend sorting. Please see the readme about customizing the filter settings for the navigation (it's already documented). By default, they are just sorted by date and optional by archive. 
For pagination you can also look into this bundle: https://github.com/heimrichhannot/contao-news-pagination-bundle
